### ISSUE TITLE
EnforceBytecodeVersion crashes on maven-enforcer-plugin 1.4.1 with a NullPointerException

### ISSUE THREAD

**Issue by mrothe** [mojohaus/extra-enforcer-rules#13]
Using the EnforceBytecodeVersion rule on maven-enforcer-plugin:1.4.1 cause a NullPointerException:

Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (checkBytecodeVersion) on project XXX: Execution checkBytecodeVersion of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution checkBytecodeVersion of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.isBadArtifact(EnforceBytecodeVersion.java:221)
        at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.checkDependencies(EnforceBytecodeVersion.java:206)
        at org.apache.maven.plugins.enforcer.EnforceBytecodeVersion.handleArtifacts(EnforceBytecodeVersion.java:132)
        at org.apache.maven.plugins.enforcer.AbstractResolveDependencies.execute(AbstractResolveDependencies.java:77)
        at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:193)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        ... 20 more

It works with enforcer 1.3.1 and 1.4.

**Comment by khmarbaise** [comment]
Do you have an example project which produces the issue?

**Comment by mrothe** [comment]
Yes, I can provide an example (unfortunally this issue tracker won't let me add a pom.xml or pom.txt as attachment :( - so I have to add the pom content directly):

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
	
	

    
    <groupId>ag.itc.test</groupId>
    <artifactId>parent</artifactId>
    <version>1-SNAPSHOT</version>

    	
    <name>Test Parent</name>
    
    
    
    <packaging>pom</packaging>
	
	 
    <dependencies>        
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>            
			<version>1.7.12</version>
			
			<scope>provided</scope>
        </dependency>
    </dependencies>    
    
    
    <properties>      		
        <enforcer.requireMavenVersion>[3.0.5,3.4)</enforcer.requireMavenVersion>		
		
        <maven-enforcer-plugin.version>1.4.1</maven-enforcer-plugin.version>       
		<enforcer-extra-rules.version>1.0-beta-3</enforcer-extra-rules.version>		
    </properties>

    
    <build>
        
        <pluginManagement>
            <plugins>	
                <plugin>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>					
					<dependencies>
						<dependency>
							<groupId>org.codehaus.mojo</groupId>
							<artifactId>extra-enforcer-rules</artifactId>
							<version>${enforcer-extra-rules.version}</version>
						</dependency>
					</dependencies>
                    <executions>
                        <execution>
						    
                            <id>enforceVersions</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
		                    <configuration>							    
								<rules>
									<requireMavenVersion>
										<version>${enforcer.requireMavenVersion}</version>
									</requireMavenVersion>
									<banDuplicatePomDependencyVersions />
								</rules>
							</configuration>
                        </execution>
						<execution>
							<id>checkBytecodeVersion</id>
							<phase>validate</phase>
							<goals>
							  <goal>enforce</goal>
							</goals>
							<configuration>
							  <skip>false</skip>
							  <rules>
								<enforceBytecodeVersion>
								  <maxJdkVersion>1.6</maxJdkVersion>
								</enforceBytecodeVersion>
							  </rules>	
							  <fail>true</fail>							  
							</configuration>
						</execution>																		
                    </executions>					 
                </plugin>		                                
            </plugins>
        </pluginManagement>
        
        <plugins>
			            
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>            
        </plugins>        
    </build>	
</project>

The problem is caused by the dependency declaration. 
If it is removed all runs fine. 
If it is defined, the rule execution crash with a NPE ... probably because a POM artifact hasn't "real" dependencies ?
But we need/use such declarations in our parent pom to force all projects to rely on some basic dependencies

**Comment by batmat** [comment]
What would be absolutely great would be to submit a PR with a new (failing)
IT. I'll personally have a look very soon if you do.

If you don't I will see if I can create one with the text you just put.
Cheers

**Comment by mrothe** [comment]
@batmat : I'm afraid I'm unable to submit such an test case as
 - I do not use Git
 - I do not know how to make a valid IT for maven plugins (knowlegde about JUnit only)

Sorry for that. 

@khmarbaise : I had a look on the changes between enforcer 1.4 and 1.4.1 to find the root cause. This led me to https://issues.apache.org/jira/browse/MENFORCER-222 and https://issues.apache.org/jira/browse/MENFORCER-156. The requiresDependencyCollection annotation cause the null file from artifact.getFile(). 
So with the return of this annotation in 1.4.1 MENFORCER-156 should be reopened as assembly fail again if used with enforcer 1.4.1:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (assemble) on project parent: Execution assemble of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at ...
Caused by: java.lang.NullPointerException
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver$DefaultFileInfo.isFile(AssemblyProxyArchiver.java:871)
        at org.apache.maven.plugin.assembly.filter.ComponentsXmlArchiverFileFilter.isSelected(ComponentsXmlArchiverFileFilter.java:193)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.acceptFile(AssemblyProxyArchiver.java:825)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.addFile(AssemblyProxyArchiver.java:450)
        at org.apache.maven.plugin.assembly.archive.task.AddArtifactTask.execute(AddArtifactTask.java:208)
        at 
...
There is a trade-off between MENFORCER-156 and MENFORCER-194, MENFORCER-222, MENFORCER-230. Some things work with enforcer 1.2, 1.3.1 and 1.4 and others with 1.3 and 1.4.1 :(

**Comment by khmarbaise** [comment]
The problem is located by using a dependency in a pom which packaging is pom which is usually bad practice nor is it really correct...Usually you should use a dependencyManagement in a parent pom like this.
